services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    init: true
    ports:
      - "14001:80"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    init: true
    depends_on:
      - backend
    ports:
      - "14002:80"
